config/routes.rb
Grapefruit::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "become" => 'admin#become', via: [:get, :post]

  devise_scope :user do
    authenticated :user do
      root 'home#dashboard', as: "authenticated_root"
    end
    unauthenticated :user do
      root 'guest#index'
    end
  end

  get 'about' => 'guest#about'
  get 'tos' => 'guest#tos'
  get 'contact' => 'guest#contact'
  get 'contribute' => 'guest#contribute'
  get 'privacy' => 'guest#privacy'

  devise_for :users, skip: [:sessions, :passwords, :registrations]

  as :user do

    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'forgot' => 'devise/passwords#new', as: :new_user_password
    post 'forgot' => 'devise/passwords#create'
    put 'forgot' => 'devise/passwords#update', as: :user_password
    get 'forgot/change' => 'devise/passwords#edit', as: :edit_user_password

    get   'join' => 'devise/registrations#new',    as: :new_user_registration
    post  'join' => 'custom_registration#create', as: :user_registration
    get 'cancel'   => 'devise/registrations#cancel', as: :cancel_user_registration
    get 'settings' => 'devise/registrations#edit',   as: :edit_user_registration
    put 'join' => 'devise/registrations#update', as: :update_user_registration

    post 'management_state' => 'home#management_state'

  end

  resources :courses do

    get 'iframe'
    get 'people'
    get 'manage'

    get 'gradelist' => 'grades#gradelist'

    resources :assignments do
      resources :submissions
      resources :grades
    end

    resources :assignment_types, only: [:index, :create, :destroy, :update]

    resources :documents, shallow: true

    resources :course_users, only: [:create, :destroy]

    resources :capsules do

      resources :documents, shallow: true

      resources :lectures do
        get :toggle_live
        get :comments
        post :submit_comment
        get :list_comments
        resources :documents, shallow: true
        resources :videos, except: :index do
          resources :video_texts, only: [:new, :create, :index, :update, :destroy]
        end
      end

      resources :problem_sets

    end

    resources :topics, only: [:new, :create, :show, :index, :destroy] do
      resources :replies, only: [:create]
    end

    resources :announcements, except: [:show]

    resources :groups

    get 'new_to_class' => 'announcements#new_to_class'
    post 'send_to_class' => 'announcements#send_to_class'

  end

end

app/controllers/guest_controller.rb
class GuestController < ApplicationController

  def index
  end

  def landing
    @login_inset = true # let template know not to force grid on form
  end

  def about
  end

  def tos
  end

  def contact
  end

  def contribute
  end

  def privacy
  end

end

app/helpers/guest_helper.rb
module GuestHelper

# pursuant to http://stackoverflow.com/questions/4081744/devise-form-within-a-different-controller
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/views/guest/_login.html.erb
<div class="header-container">
  <div class="row">

    <div class="small-12 large-6 large-offset-3 columns login-form-container">
      <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: "login-form" }) do |f| %>

        <fieldset>
          <%= f.email_field :email, autofocus: true, placeholder: "Email", class: "large" %>
          <%= f.password_field :password, placeholder: "Password", class: "large" %>
          <%= f.submit "Login", class: "button success" %>

          <% if admin_user_signed_in? %>
            <p>Or, <%= link_to 'login with a user ID', become_path %> as an admin. </p>
          <% end %>

          <div class="center">
            <% if request.post? %>
              <%= link_to "Forgot password?",
                new_password_path(resource_name),
                class: "button success" %>
            <% end %>

            <%= link_to "Make your free #{Settings.instance.name} account!",
              new_registration_path(resource_name),
              class: "button expand" %>

            <h4>What is Grapefruit?</h4>

            <p>
              <%= link_to 'Learn more about Grapefruit',
                Settings.instance.info_url,
                class: "button small secondary" %>
            </p>

            <%= render "devise/shared/links" %>
          </div>
        </fieldset>

      <% end %>
    </div>
  </div>
</div>

app/views/guest/about.html.erb
<div class="about content">
  <h2>About</h2>
  <p>Grapefruit is an open-source LMS. Grapefruit Cloud is an inexpensive, convenient and secure hosting platform that allows students and instructors to access and edit content from anywhere. </p>
  <p>The open-source Grapefruit project received financial support from the excellent Rensselaer Center for Open Source Software, <%= link_to 'RCOS', 'http://rcos.rpi.edu' %>,
  which is funded entirely by generous donations from people like you. </p>
  <p>Grapefruit is released under the GPL License (version 3).
    Contributions are <%= link_to 'welcome', GITHUB_URL, :target => '_blank' %>.</p>
</div>

app/views/guest/contact.html.erb
<div class="contact content">

  <h2>Contact / Help</h2>

  <p>
    If you need help with a course or other academic activities, please get in touch with your professor or teaching assistant.
  </p>

  <p>
    For bug reports or help questions about the Grapefruit platform, please contact the Grapefruit team at <%= help_email %>.
  </p>

  <p>
    For collaboration inquiries or other requests, please contact Graham Ramsey at <strong>g at graham dot li</strong>.
  </p>

</div>

app/views/guest/contribute.html.erb
<div class="contribute content">

  <h2>Contributing to Grapefruit</h2>

  <p>
    Contributions are always welcome! Visit our <%= link_to 'Github page', GITHUB_URL %> to learn more.
  </p>

  <p>If you are a part of (or represent) an academic institution or business and would like to explore collaboration or more
  formal contribution, please <%= link_to 'contact us', contact_url %>.</p>

</div>

app/views/guest/index.html.erb
<%= render 'guest/login' %>

app/views/guest/landing.html.erb
<div class="landing content">

  <p class="description">Grapefruit is an open-source initiative pioneered by RCOS to bring<br/> Rensselaer courses to your laptop, desktop, or phone.</p>

  <%= link_to "Login", new_user_session_path, class: "button large login" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "button large success" %>

</div>

app/views/guest/tos.html.erb
<div class="tos content">
  <h2>Terms &amp; Conditions</h2>
  <p>Place 90-100 pages of legalese here.</p>
</div>