config/routes.rb
Grapefruit::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "become" => 'admin#become', via: [:get, :post]

  devise_scope :user do
    authenticated :user do
      root 'home#dashboard', as: "authenticated_root"
    end
    unauthenticated :user do
      root 'guest#index'
    end
  end

  get 'about' => 'guest#about'
  get 'tos' => 'guest#tos'
  get 'contact' => 'guest#contact'
  get 'contribute' => 'guest#contribute'
  get 'privacy' => 'guest#privacy'

  devise_for :users, skip: [:sessions, :passwords, :registrations]

  as :user do

    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'forgot' => 'devise/passwords#new', as: :new_user_password
    post 'forgot' => 'devise/passwords#create'
    put 'forgot' => 'devise/passwords#update', as: :user_password
    get 'forgot/change' => 'devise/passwords#edit', as: :edit_user_password

    get   'join' => 'devise/registrations#new',    as: :new_user_registration
    post  'join' => 'custom_registration#create', as: :user_registration
    get 'cancel'   => 'devise/registrations#cancel', as: :cancel_user_registration
    get 'settings' => 'devise/registrations#edit',   as: :edit_user_registration
    put 'join' => 'devise/registrations#update', as: :update_user_registration

    post 'management_state' => 'home#management_state'

  end

  resources :courses do

    get 'iframe'
    get 'people'
    get 'manage'

    get 'gradelist' => 'grades#gradelist'

    resources :assignments do
      resources :submissions
      resources :grades
    end

    resources :assignment_types, only: [:index, :create, :destroy, :update]

    resources :documents, shallow: true

    resources :course_users, only: [:create, :destroy]

    resources :capsules do

      resources :documents, shallow: true

      resources :lectures do
        get :toggle_live
        get :comments
        post :submit_comment
        get :list_comments
        resources :documents, shallow: true
        resources :videos, except: :index do
          resources :video_texts, only: [:new, :create, :index, :update, :destroy]
        end
      end

      resources :problem_sets

    end

    resources :topics, only: [:new, :create, :show, :index, :destroy] do
      resources :replies, only: [:create]
    end

    resources :announcements, except: [:show]

    resources :groups

    get 'new_to_class' => 'announcements#new_to_class'
    post 'send_to_class' => 'announcements#send_to_class'

  end

end

app/models/announcement.rb
# == Schema Information
#
# Table name: announcements
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text(65535)
#  course_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Announcement < ActiveRecord::Base

  # Validations
  # ========================================================
  validates :title, presence: true
  validates :content, presence: true

  # Relationships
  # ========================================================
  belongs_to :course

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :get_announcement, only: [:edit, :update, :destroy]
  before_filter :get_course

  layout "course"

  def new_to_class
    authorize! :manage, @course
  end

  def send_to_class
    authorize! :manage, @course
    @course.students.each do |student|
      UserMailer.new_announcement(current_user, student, @course, params[:subject], params[:message]).deliver_later
    end
    flash[:success] = "Email sent!"
    redirect_to course_announcements_path(@course)
  end

  def new
    @announcement = @course.announcements.new
    authorize! :manage, @course
  end

  def create
    @announcement = @course.announcements.new(announcement_params)
    authorize! :manage, @course

    if @announcement.save
      flash[:success] = "Announcement created!"
      if(params[:send_email])
        @course.students.each do |student|
          UserMailer.new_announcement(current_user, student, @course, @announcement.title, @announcement.content).deliver_later
        end
      end
      redirect_to course_announcements_path(@course)
    else
      render "new"
    end
  end

  def index
    authorize! :read, @course
    @announcements = @course.announcements.order("created_at DESC").paginate(page: params[:page])
  end

  def edit
    authorize! :manage, @course
  end

  def update
    authorize! :manage, @course

    if @announcement.update_attributes(announcement_params)
      flash[:success] = "Announcement updated!"
      redirect_to course_announcements_path(@course)
    else
      render "edit"
    end
  end

  def destroy
    authorize! :manage, @course
    @announcement.destroy
    flash[:success] = "Announcement deleted!"
    redirect_to [@course, @announcement]
  end

private

  def get_announcement
    @announcement = Announcement.find(params[:announcement_id] || params[:id])
    unless @announcement.present?
      flash[:error] = "Invalid announcement!"
      redirect_to root_path
    end
  end

  def announcement_params
    params.require(:announcement).permit(:title, :content)
  end

end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_announcement.html.erb
<tr>
  <td>
    <%= announcement.title %>
  </td>

  <td>
    <span class="pre"><%= announcement.content %></span>
  </td>

  <td>
    <% if can? :manage, @course %>
      <%= link_to "Edit",
          edit_course_announcement_path(@course, announcement),
          class: "button small" %>
      <%= link_to 'Delete',
          [@course, announcement],
          confirm: ("Are you sure you want to delete this announcement?"),
          method: :delete,
          class: "button small alert" %>
    <% end %>
  </td>
</tr>

app/views/announcements/edit.html.erb
<% page_title "Editing #{@announcement.title}" %>

<div class="landing">

  <%= link_to '&larr; cancel to announcements'.html_safe, course_announcements_path(@course), class: 'button secondary small' %>

  <div class="description">
    <h3>Edit <%= @announcement.title %></h3>
  </div>

  <div class="login">
    <%= form_for [@course, @announcement] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.text_field :title, placeholder: "Homework due tommorrow!", autofocus: true %>

      <%= f.text_area :content, rows: 4, style: "height:auto;", placeholder: "Pages 47-48 problems are due tomorrow, make sure to turn them in!" %>

      <div><%= f.submit "Modify Announcement", class: "button small" %></div>
    <% end %>
  </div>

</div>

app/views/announcements/index.html.erb
<% page_title "Announcements" %>

<div class="landing">

  <div class="description">
    <h3>Announcements for <%= @course.name %></h3>
  </div>

  <% if can? :manage, @course %>
    <%= link_to "Add Announcement", new_course_announcement_path(@course), class: "button small" %>
    <%= link_to "Send Email to Students", course_new_to_class_path(@course), class: "button small secondary" %>
  <% end %>

  <table class="">
    <thead>
      <th width="200">Title</th>
      <th width="400">Content</th>
      <% if can? :manage, @course %>
        <th width="150">Actions</th>
      <% end %>
    </thead>
      <tbody>
        <% if @announcements.empty? %>
          <tr>
            <td colspan="4">
              <span>No announcements found.</span>
            </td>
          </tr>
        <% end %>
        <%= render @announcements, full: true %>
      </tbody>
  </table>

  <div class="pages">
    <%= will_paginate @announcements %>
  </div>
</div>

app/views/announcements/new.html.erb
<% page_title "Creating New Announcement" %>

<div class="landing">

  <%= link_to '&larr; cancel to announcements'.html_safe, course_announcements_path(@course), class: 'button secondary small' %>

  <div class="description">
    <h3>Add Announcement to <%= @course.name %></h3>
  </div>

  <div class="login">
    <%= form_for [@course, @announcement] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.text_field :title, placeholder: "Homework due tommorrow!", autofocus: true %>

      <%= f.text_area :content, rows: 4, style: "height:auto;", placeholder: "Pages 47-48 problems are due tomorrow, make sure to turn them in!" %>

      <%= render 'global/send_email', checked: true %>

      <div><%= f.submit "Create Announcement", class: "button small" %></div>
    <% end %>
  </div>

</div>

app/views/announcements/new_to_class.html.erb
<div class="landing">

  <%= link_to '&larr; announcements'.html_safe, course_announcements_path(@course), class: 'button secondary small' %>

  <div class="description">
    <h3>Send Email to Students in <%= @course.name %></h3>
  </div>

  <div class="login">

    <%= form_tag(course_send_to_class_path(@course)) do %>
      <%= text_field_tag :subject, nil, placeholder: "Email Subject", autofocus: true %>
      <%= text_area_tag :message, nil, style: "height:10em", placeholder: "Message" %>
      <%= submit_tag "Send Email", class: "button small" %>
    <% end %>

  </div>

</div>