config/routes.rb
Grapefruit::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "become" => 'admin#become', via: [:get, :post]

  devise_scope :user do
    authenticated :user do
      root 'home#dashboard', as: "authenticated_root"
    end
    unauthenticated :user do
      root 'guest#index'
    end
  end

  get 'about' => 'guest#about'
  get 'tos' => 'guest#tos'
  get 'contact' => 'guest#contact'
  get 'contribute' => 'guest#contribute'
  get 'privacy' => 'guest#privacy'

  devise_for :users, skip: [:sessions, :passwords, :registrations]

  as :user do

    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'forgot' => 'devise/passwords#new', as: :new_user_password
    post 'forgot' => 'devise/passwords#create'
    put 'forgot' => 'devise/passwords#update', as: :user_password
    get 'forgot/change' => 'devise/passwords#edit', as: :edit_user_password

    get   'join' => 'devise/registrations#new',    as: :new_user_registration
    post  'join' => 'custom_registration#create', as: :user_registration
    get 'cancel'   => 'devise/registrations#cancel', as: :cancel_user_registration
    get 'settings' => 'devise/registrations#edit',   as: :edit_user_registration
    put 'join' => 'devise/registrations#update', as: :update_user_registration

    post 'management_state' => 'home#management_state'

  end

  resources :courses do

    get 'iframe'
    get 'people'
    get 'manage'

    get 'gradelist' => 'grades#gradelist'

    resources :assignments do
      resources :submissions
      resources :grades
    end

    resources :assignment_types, only: [:index, :create, :destroy, :update]

    resources :documents, shallow: true

    resources :course_users, only: [:create, :destroy]

    resources :capsules do

      resources :documents, shallow: true

      resources :lectures do
        get :toggle_live
        get :comments
        post :submit_comment
        get :list_comments
        resources :documents, shallow: true
        resources :videos, except: :index do
          resources :video_texts, only: [:new, :create, :index, :update, :destroy]
        end
      end

      resources :problem_sets

    end

    resources :topics, only: [:new, :create, :show, :index, :destroy] do
      resources :replies, only: [:create]
    end

    resources :announcements, except: [:show]

    resources :groups

    get 'new_to_class' => 'announcements#new_to_class'
    post 'send_to_class' => 'announcements#send_to_class'

  end

end

app/models/lecture.rb
# == Schema Information
#
# Table name: lectures
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  lecture_number :integer
#  created_at     :datetime
#  updated_at     :datetime
#  capsule_id     :integer
#  description    :text(65535)
#  live           :boolean          default(FALSE)
#

class Lecture < ActiveRecord::Base

  # Validations
  # ========================================================
  validates :name, presence: true

  # Relationships
  # ========================================================
  has_many :documents, dependent: :destroy

	belongs_to :capsule

  has_many :videos
  has_many :comments, class_name: "Comment", dependent: :destroy

end

app/controllers/api/v1/lectures_controller.rb
class API::V1::LecturesController < API::V1::ApplicationController

  before_filter :authenticate_user_from_token!
  before_filter :get_course
  before_filter :get_capsule
  before_filter :get_lecture

  def show
  end

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController

  before_filter :get_course
  before_filter :get_capsule
  before_filter :get_all_course_capsules, only: [:new, :show, :edit]
  before_filter :get_lecture, except: [:create, :new]
  before_filter :authenticate_user!

  layout "course"

	def new
  	@lecture = @capsule.lectures.new
  end

  def create
    @lecture = @capsule.lectures.new(lecture_params)
    if @lecture.save
      flash[:success] = "Lecture created!"
      redirect_to course_manage_path(@course)
    else
      render 'new'
    end
  end

  def show
    authorize! :show, @lecture
  	@lecture = @capsule.lectures.find(params[:id])
    @capsules = @lecture.capsule.course.capsules

    @videos = @lecture.videos.order("created_at ASC")
    @videos.build
    
    @documents = @lecture.documents
  end

  def edit
    authorize! :update, @lecture
  end

  def update
    authorize! :update, @lecture
    if @lecture.update_attributes(lecture_params)
      flash[:success] = "Lecture updated!"
      redirect_to course_manage_path(@course)
    else
      render "edit"
    end
  end

  def toggle_live
    authorize! :update, @lecture
    @lecture.toggle(:live)
    @lecture.save
    redirect_to [@course, @capsule, @lecture]
  end

  def comments
    authorize! :show, @lecture
    @comment = @lecture.comments.new
    render layout: "home"
  end

  def submit_comment
    authorize! :show, @lecture
    comment_params = params.require(:comment).permit(:body)
    @comment = @lecture.comments.new(comment_params)
    @comment.author = current_user
    if not @lecture.live
      render json: {error: true}
    elsif @comment.save
      render json: {success: true}
    else
      render json: {error: true}
    end
  end

  def list_comments
    authorize! :show, @lecture
    render json: @lecture.comments.order('created_at ASC').limit(50)
  end

  def destroy
    authorize! :destroy, @lecture
  	@lecture.destroy
  	redirect_to :back
  end

private

  def get_lecture
    @lecture = @capsule.lectures.find(params[:lecture_id] || params[:id])
    @live_button = (@lecture.live) ? 'End Lecture' : 'Make Lecture Live';
  end

  def lecture_params
    params.require(:lecture).permit(:name, :description, :lecture_number,
                                    :mediasite_url, :live)
  end

end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_lecture.html.erb
<li>
  <% if lecture == @lecture %>
    <strong><%= @lecture.name %> &rsaquo;</strong>
  <% else %>
    <%= link_to lecture.name, [lecture.capsule.course, lecture.capsule, lecture] %>
  <% end %>
</li>

app/views/lectures/_manage_lecture.html.erb
<div class="lecture-container">

  <h5>
    Lecture:
    <%= link_to lecture.name, "#", class: "slide-reveal", data: { reveal: 'lecture-' + lecture.id.to_s } %>
  </h5>

  <div class="lecture reveal-hidden" id="lecture-<%= lecture.id %>">

    <p>
      <%= link_to "edit lecture info",
        edit_course_capsule_lecture_path(@course, lecture.capsule, lecture), class: "add" %>
      <span class="space"></span>
      <%= link_to "show files", "#",
          class: "add secondary slide-reveal",
          data: {
            reveal: 'lecture-' + lecture.id.to_s + '-files',
            initial: "manage files #{parens(lecture.documents.count)}",
            active: 'done with files'
          } %>
      <%= link_to "view as student &#10148;".html_safe,
            course_capsule_lecture_path(@course, lecture.capsule, lecture),
            class: "add secondary" %>
      <span class="space"></span>

    </p>

    <div id="lecture-<%= lecture.id %>-files" class="reveal-hidden panel">

      <% if lecture.documents.empty? %>
        <p>No lecture files yet!</p>
      <% else %>
        <h6>Lecture Files (examples: presentations, homework, etc)</h6>
      <% end %>

      <%= render "documents/documents", container: lecture, documents: lecture.documents %>

      <h5><%= link_to "add file",
        new_course_capsule_lecture_document_path(@course, lecture.capsule, lecture), class: "" %>
      </h5>

    </div>

    <div class="lecture-videos">
      <% if lecture.videos.present? %>
        <div>
          <h6>lecture videos (<%= link_to "new video", new_course_capsule_lecture_video_path(@course, lecture.capsule, lecture), style: "font-weight:bold;" %>)</h6>
          <% lecture.videos.each do |video| %>
            <%= render 'videos/manage_video', video: video %>
          <% end %>
        </div>
      <% else %>
        <p class="grey">
          There aren't any videos in this lecture yet.
          <%= link_to "add video", new_course_capsule_lecture_video_path(@course, lecture.capsule, lecture), class: "add" %>
        </p>
      <% end %>
    </div>

  </div>

</div>

app/views/lectures/_table_lecture.html.erb
<tr class="capsule-item">
  <td>
    <%= link_to "#{lecture.lecture_number}. #{lecture.name}", [lecture.capsule.course, lecture.capsule, lecture], class: "item-name" %>
  </td>
</tr>

app/views/lectures/comments.html.erb
<div class="live-discussion">

  <h3>live discussion: <%= link_to @lecture.name, [@course, @capsule, @lecture]%></h3>
  <p><%= link_to 'Close', 'javascript:window.close()', class: "button small" %></p>

  <% if @lecture.live %>

    <div class="comments-submit-container">

      <%= form_for @comment, url: {action: "submit_comment"}, method: 'post', remote: true, html: {id: "comments-submit"} do |f| %>
        <%= f.text_field :body, placeholder: "Message", autofocus: true, id: "comment-body" %>
        <%= f.submit 'Post Comment', class: 'button postfix' %>
      <% end %>

    </div><br/>

  <% end %>

  <% if not @lecture.live %>
     <div class="alert-box info">
      This lecture is not currently live. Comments are read-only if present.
    </div>
  <% end %>

  <div id="lecture-comments"
    data-lecture-id="<%= @lecture.id %>"
    data-url="<%= course_capsule_lecture_list_comments_path(@course, @capsule, @lecture) %>">
    <p class='empty'>Loading comments...</p>
  </div>

</div>

app/views/lectures/edit.html.erb
<% page_title "Editing #{@lecture.name}" %>

<div class="landing">

  <div class="description">
    <h3>Edit "<%= @lecture.name %>"</h3>
  </div>

  <div class="login">
    <%= form_for [@course, @capsule, @lecture] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.text_field :name, placeholder: "Name", autofocus: true %>

      <%= f.text_area :description, style: "height: 20em", placeholder: "This lecture will focus on ..." %>

      <div>
        <%= f.submit "Update Lecture", class: "button small" %>
        <%= link_to "Delete Lecture",
                  course_capsule_lecture_path(@course, @lecture.capsule, @lecture),
                  data: { confirm: "Are you want to delete this lecture? This action cannot be undone." },
                  method: :delete,
                  class: "button alert small" %>
      </div>
    <% end %>
  </div>

</div>

app/views/lectures/new.html.erb
<% page_title "Creating New Lecture" %>

<%= breadcrumbs([
      link_to("All Courses", courses_path),
      link_to(@course.name, course_path(@course)),
      link_to(@capsule.name, [@course, @capsule]),
      link_to('Add Lecture', void, class: "current")
    ])
%>

<div class="landing">

  <div class="description">
    <h3>Add Lecture to <%= @capsule.name %></h3>
  </div>

  <div class="login">
    <%= form_for [@course, @capsule, @lecture] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.text_field :name, placeholder: "Name", autofocus: true %>

      <%= f.text_area :description, placeholder: "This lecture will focus on ..." %>

      <div><%= f.submit "Add Lecture", class: "button small" %></div>
    <% end %>
  </div>

</div>

app/views/lectures/show.html.erb
<% page_title @lecture.name %>

<h2><%= @lecture.name %> <sup><%= 'LIVE &#149;'.html_safe if @lecture.live %></sup></h2>

<% if can? :manage, @course %>
  <%= link_to (@lecture.live ? "stop live comments" : "make lecture live"),
    course_capsule_lecture_toggle_live_path(@course, @capsule, @lecture), class: "button small" %>
<% end %>

<% if @lecture.live %>
  <%= link_to 'Live Feed &nbsp; &#10148;'.html_safe, course_capsule_lecture_comments_path(@course, @capsule, @lecture),
  class: "button small secondary", target: "_blank" %>
<% end %>

<%= link_to_textbook_problem_sets(@course) %>

<% unless @lecture.description.blank? %>
  <p class="description lecture-description"><%= @lecture.description %></p>
<% end %>

<%= render "documents/documents", container: @lecture %>

<% if @videos.present? %>
  <div>
    <h3>Videos</h3>
    <% @videos.each do |video| %>
      <%= render video %>
      <% if @videos.length > 1 %>
        <div class="custom-hr"></div>
      <% end %>
    <% end %>
  </div>
<% end %>

<% if @documents.empty? && @videos.empty? %>
  <p class="grey">Looks like there's no content in this lecture yet!</p>
<% end %>