config/routes.rb
Grapefruit::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "become" => 'admin#become', via: [:get, :post]

  devise_scope :user do
    authenticated :user do
      root 'home#dashboard', as: "authenticated_root"
    end
    unauthenticated :user do
      root 'guest#index'
    end
  end

  get 'about' => 'guest#about'
  get 'tos' => 'guest#tos'
  get 'contact' => 'guest#contact'
  get 'contribute' => 'guest#contribute'
  get 'privacy' => 'guest#privacy'

  devise_for :users, skip: [:sessions, :passwords, :registrations]

  as :user do

    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'forgot' => 'devise/passwords#new', as: :new_user_password
    post 'forgot' => 'devise/passwords#create'
    put 'forgot' => 'devise/passwords#update', as: :user_password
    get 'forgot/change' => 'devise/passwords#edit', as: :edit_user_password

    get   'join' => 'devise/registrations#new',    as: :new_user_registration
    post  'join' => 'custom_registration#create', as: :user_registration
    get 'cancel'   => 'devise/registrations#cancel', as: :cancel_user_registration
    get 'settings' => 'devise/registrations#edit',   as: :edit_user_registration
    put 'join' => 'devise/registrations#update', as: :update_user_registration

    post 'management_state' => 'home#management_state'

  end

  resources :courses do

    get 'iframe'
    get 'people'
    get 'manage'

    get 'gradelist' => 'grades#gradelist'

    resources :assignments do
      resources :submissions
      resources :grades
    end

    resources :assignment_types, only: [:index, :create, :destroy, :update]

    resources :documents, shallow: true

    resources :course_users, only: [:create, :destroy]

    resources :capsules do

      resources :documents, shallow: true

      resources :lectures do
        get :toggle_live
        get :comments
        post :submit_comment
        get :list_comments
        resources :documents, shallow: true
        resources :videos, except: :index do
          resources :video_texts, only: [:new, :create, :index, :update, :destroy]
        end
      end

      resources :problem_sets

    end

    resources :topics, only: [:new, :create, :show, :index, :destroy] do
      resources :replies, only: [:create]
    end

    resources :announcements, except: [:show]

    resources :groups

    get 'new_to_class' => 'announcements#new_to_class'
    post 'send_to_class' => 'announcements#send_to_class'

  end

end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id            :integer          not null, primary key
#  file          :string(255)
#  description   :text(65535)
#  created_at    :datetime
#  updated_at    :datetime
#  course_id     :integer
#  capsule_id    :integer
#  lecture_id    :integer
#  assignment_id :integer
#  submission_id :integer
#  grade_id      :integer
#  group_id      :integer
#

class Document < ActiveRecord::Base

  # Files
  # ========================================================
  mount_uploader :file, DocumentUploader

  # Validations
  # ========================================================
  validates :file, presence: true

  # Relationships
  # ========================================================
  belongs_to :course
  belongs_to :capsule
  belongs_to :lecture
  belongs_to :submission
  belongs_to :assignment
  belongs_to :grade
  belongs_to :group

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_filter :get_owners
  before_filter :get_container
  before_filter :authenticate_user!

  layout "course"

  def new
    @document = @container.documents.new
    authorize! :create, @document
  end

  def create

    @document = @container.documents.new(document_params)

    authorize! :create, @document

    if @document.save
      flash[:success] = "File added!"
      redirect_to @redirect
    else
      render 'new'
    end

  end

  def destroy
    @document = Document.find(params[:id])
    authorize! :delete, @document
    name = @document[:file]
    @document.destroy
    flash[:success] = "#{name} was deleted!"
    if @document.assignment
      redirect_to edit_course_assignment_path(@document.assignment.course, @document.assignment)
    elsif @document.grade
      redirect_to course_assignment_grades_path(@document.grade.assignment.course, @document.grade.assignment)
    elsif @document.lecture
      redirect_to course_manage_path(@document.lecture.capsule.course)
    elsif @document.capsule
      redirect_to course_manage_path(@document.capsule.course)
    else
      redirect_to course_manage_path(@document.course)
    end
  end

  private
  def get_owners
    if params[:course_id]
       get_course
     end
    if params[:capsule_id]
      get_capsule
    end
    if params[:lecture_id]
      get_lecture
    end
  end

  private
  def get_container
    if @lecture
      @container = @lecture
      @redirect = course_manage_path(@lecture.capsule.course)
    elsif @capsule
      @container = @capsule
      @redirect = course_manage_path(@capsule.course)
    elsif @course
      @container = @course
      @redirect = course_manage_path(@course)
    end
  end

private

  def document_params
    params.require(:document).permit(:file, :description)
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
  def document_form(document)
    if document.lecture
      [@course, @capsule, @lecture, @document]
    elsif document.capsule
      [@course, @capsule, @document]
    elsif document.course
      [@course, @document]
    end
  end
end

app/views/documents/_document.html.erb
<tr>
  <td>
    <%= link_to (if document.description? then document.description else document[:file] end), 
          document.file.url,
          target: "_blank" %>
  </td>
  <td class="center">
    <%= document.file.file.extension %>
  </td>
  <% if can? :delete, document %>
    <td class="center">
      <%= link_to 'Delete', document, confirm: ("Are you sure you want to delete " + document[:file] + "?"), method: :delete %>
    </td>
  <% end %>
</tr>

app/views/documents/_documents.html.erb
<%
  # Optional local variables that can be passed in
  table_class ||= "listing"
  documents ||= @documents
%>

<% if documents.present? %>
  <table class="<%= table_class %>">
    <thead>
      <th width="50%">File</th>
      <th width="25%" class="center">Type</th>
      <% if can? :manage, container %>
        <th width="25%" class="center">Actions</th>
      <% end %>
    </thead>
    <tbody>
      <%= render documents %>
    </tbody>
  </table>
<% elsif container.instance_of?(Assignment) %>
  <p class="grey">No documents found.</p>
<% end %>

app/views/documents/new.html.erb
<%= breadcrumbs([
      link_to('All Courses', courses_path),
      (link_to(@course.name, course_path(@course)) if @course) || "",
      (link_to(@capsule.name, course_capsule_path(@course, @capsule)) if @capsule) || "",
      (link_to(@lecture.name, course_capsule_lecture_path(@course, @capsule, @lecture)) if @lecture) || "",
      link_to('Add File', void, class: "current")
    ]) %>

<div class="landing">

  <div class="description">
    <h2>Add File to '<%= @container.name %>'</h2>
  </div>

  <div class="login">
    <%= form_for document_form(@document) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <div class="row">
        <div class="large-3">
          <%= f.label :file, "Choose File: " %>
        </div>
        <div class="large-9">
          <%= f.file_field :file %>
        </div>
      </div>

      <%= f.text_field :description, placeholder: "Optional Description" %>

      <div><%= f.submit "Upload File", class: "button small", id: "document_file_button" %></div>

    <% end %>
  </div>

</div>